name: Doxygen

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen Documentation
      run: doxygen doxygen/Doxyfile
    
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: doxygen/build/html

  deploy:
    needs: build

    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest 
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
