name: Build esp32

on:
  workflow_dispatch:
  push:
  pull_request:

defaults:
  run:
    working-directory: ./esp32

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: esp32/.pio/build/
  
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run static code analysis
        run: pio check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linter
        working-directory: ./esp32
        run: >
          find .
          \( -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" \)
          -type f |
          xargs clang-format -n -i -Werror --verbose --style=Google
